imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.2
      commands:
        - composer install --no-interaction --prefer-dist --optimize-autoloader
        - mkdir -p docs
        - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

artifacts:
  paths:
    - docs/coverage.clover

tools:
  external_code_coverage:
    enabled: true
