tools:
  php_code_coverage: true

imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage

      dependencies:
        before:
          - composer install

      tests:
        override:
          - command: composer phpunit:coverage
            coverage:
              file: var/coverage.clover
              format: php-clover
