imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        analysis:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 16
            cache:
                directories:
                    - vendor/
                    - node_modules/
            commands:
                - npm cache clean --force
                - npm install --verbose --no-progress
                - mkdir -p docs
                - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
                - php-scrutinizer-run

tools:
    external_code_coverage:
        timeout: 600
        runs: true
