imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-jammy

    environment:
        node:
            version: "18"

    nodes:
     analysis:
    tests:
      commands:
        - composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader
        - vendor/bin/phpunit --coverage-clover=docs/coverage.clover
      coverage:
        file: "docs/coverage.clover"
        format: "php-clover"
