tools:
  php_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer: true
  php_cpd: true
  php_loc: true
  php_pdepend: true
  php_sim: true
  php_cs_fixer: true

imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

coding_style:
  php:
    code_sniffer:
      config:
        standard: PSR2

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage

      dependencies:
        before:
          - composer install

      tests:
        override:
          - command: composer phpunit:coverage
            coverage:
              file: var/coverage.clover
              format: php-clover
