tools:
  php_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer: true
  php_cpd: true
  php_loc: true
  php_pdepend: true
  php_sim: true

imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

coding_style:
  php:
    braces: true
    indentation: 4
    spaces: true
    upper_lower_casing: true

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage

      dependencies:
        before:
          - composer install

      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=var/coverage.clover
            coverage:
              file: var/coverage.clover
              format: php-clover
