imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: php:8.1

    environment:
        node:
            version: "18"

    nodes:
        analysis:
            tests:
                override:
                    - command: "composer install --no-interaction"
                    - command: "composer phpunit -- --coverage-clover=docs/coverage.clover"
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"
