imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  nodes:
    my-tests:
      environment:
        php:
          version: 8.1.13
          ini:
            xdebug.mode: coverage

      tests:
        override:
          - command: "composer phpunit:coverage && ls -la var"
            coverage:
              file: "var/coverage.clover"
              format: "php-clover"
