environment:
  php:
    version: '8.1'
  node:
    version: '16'

build:
  nodes:
    analysis:
      environment:
        php:
          version: '8.1'
      # eventuella byggsteg och kommandon

tools:
  phpunit:
    config: phpunit.xml
    run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
