imports:
    - php

filter:
    excluded_paths:
        - vendor/*
        - tests/*

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1
                    variables:
                        XDEBUG_MODE: coverage

tests:
    override:
        - command: "composer phpunit:coverage"
          coverage:
            file: "var/coverage.clover"
            format: "php-clover"
