build:
  image: default-bionic

  nodes:
    analysis:
      environment:
        php:
          version: 8.2
        node:
          version: 16
      cache:
        directories:
          - vendor/
          - node_modules/
      commands:
        - pwd                  # Visa nuvarande arbetskatalog
        - ls -la              # Lista alla filer och mappar
        - cd /home/scrutinizer/me-report  # Navigera till rätt katalog
        - ls -la              # Lista filer i me-report för att bekräfta
        - npm install          # Installera npm-paket
        - mkdir -p docs
        - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
        - php-scrutinizer-run
