build:
  environment:
    php:
      version: '8.1'

  nodes:
    default:
      commands:
        - composer install --no-interaction --prefer-dist
        - mkdir -p build/logs
        - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

tools:
  php_analyzer:
    enabled: true

filter:
  excluded_paths:
    - tests/*
    - vendor/*
