imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.2  # Byt till 8.2 för kompatibilitet
      tests:
        override:
          - mkdir -p docs && XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

before_commands:
  - echo "Setup commands can go here if needed"

artifacts:
  paths:
    - docs/coverage.clover

tools:
  external_code_coverage:
    enabled: true
