imports:
    - php

filter:
    excluded_paths:
        - vendor/*
        - test/*

build:
    image: default

    nodes:
        analysis:
            environment:
                php:
                    version: 8.3
                node:
                    version: 16
            cache:
                directories:
                    - vendor/
                    - node_modules/
            project_setup:
                override:
                    - npm ci || npm install
            tests:
                override:
                    - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
            commands:
                - php-scrutinizer-run
