# skapa mappar som behövs innan testkörning
before_commands:
  - mkdir -p build/logs

# bygg steg, installera beroenden
build:
  nodes:
    scrutinizer:
      # jobba i roten av projektet
      root_path: .
      # kommandon som körs i byggfasen
      commands:
        - composer install --no-interaction --prefer-dist

# test steg, kör phpunit
tests:
  override:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=build/logs/clover.xml

# rapportering av kodtäckning till Scrutinizer
artifacts:
  - build/logs/clover.xml

checks:
  php:
    # aktivera kodtäckning
    code_coverage:
      enabled: true
