build:
  image: default-bionic

  nodes:
    analysis:
      environment:
        php:
          version: 8.2
        node:
          version: 16
      cache:
        directories:
          - vendor/
          - node_modules/
      commands:
        - pwd
        - echo "Checking directory contents"
        - ls -la
        - echo "Checking if package.json exists"
        - test -f package.json && echo "Found package.json" || echo "package.json missing!"
        - npm ci || npm install
        - mkdir -p docs
        - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
        - php-scrutinizer-run
