tools:
  php_code_coverage: true

imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

build:
  image: default-bionic

  nodes:
    analysis:
      environment:
        php:
          version: 8.1.13
          ini:
            xdebug.mode: coverage

      dependencies:
        before:
          - composer install

      tests:
        override:
          - command: composer phpunit:coverage

external_code_coverage:
  format: php-clover
  file: var/coverage.clover
