build:
    image: default-bionic

    nodes:
        analysis:
            environment:
                php:
                    version: 8.2
                node:
                    version: 16
            cache:
                directories:
                    - vendor/
                    - node_modules/
            commands:
                - ls -la
                - npm ci || npm install
                - mkdir -p docs
                - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover || true
                - php-scrutinizer-run || true
