imports:
    - php

filter:
    excluded_paths:
        - vendor/*
        - test/*

build:
    image: default-bionic

    nodes:
        analysis:
            environment:
                php:
                    version: 8.3
                node:
                    version: 16
            cache:
                directories:
                    - vendor/
                    - node_modules/
            commands:
                - npm ci || npm install
                - mkdir -p docs
                - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
                - php-scrutinizer-run
