build:
    environment:
        php:
            version: 8.3
        node: true
        dependencies:
            before:
                - composer install --no-interaction
            override:
                - npm install
    tests:
        override:
            - command: vendor/bin/phpunit --coverage-clover=var/coverage.clover
              coverage:
                  file: var/coverage.clover
                  format: php-clover

filter:
    excluded_paths:
        - tests/*
        - var/*
        - config/*
        - public/*
        - tools/*
        - vendor/*

tools:
    php_code_sniffer: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: false
    external_code_coverage: true
