imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  commands:
    - curl -sL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm install

  nodes:
    tests:
      environment:
        php:
          version: 8.3.3
          ini:
            xdebug.mode: coverage

      tests:
        override:
          - command: >
              mkdir -p docs &&
              ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

tools:
  external_code_coverage:
    enabled: true
