imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 20

        analysis:
            tests:
                override:
                    - php-scrutinizer-run

    tests:
        override:
            - command: >
                npm cache clean --force &&
                npm install --verbose --no-progress &&
                mkdir -p docs &&
                ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
    after:
        - php-scrutinizer-run --coverage docs/coverage.clover

tools:
    external_code_coverage:
        enabled: true
