build:
  nodes:
    scrutinizer__default:
      environment:
        php:
          version: '8.1'
      commands:
        - composer install --no-interaction --prefer-dist
        - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

tools:
  php_code_coverage:
    formats:
      - clover: build/logs/clover.xml

checks:
  php_code_coverage:
    enabled: true
