.scrutinizer.yml:before_commands:
  - mkdir -p build/logs

build:
  nodes:
    scrutinizer:
      root_path: .
      commands:
        - composer install --no-interaction --prefer-dist

tests:
  override:
    - vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=build/logs/clover.xml

artifacts:
  - build/logs/clover.xml

checks:
  php:
    # code_coverage:
    #   enabled: true
    coding_standard: PSR2
