imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default

    nodes:
        analysis:
            project_setup:
                override:
                    - 'composer install'
            tests:
                override:
                    - command: 'vendor/bin/phpunit --coverage-clover=docs/coverage.clover'
                      coverage:
                          file: 'docs/coverage.clover'
                          format: 'php-clover'
