build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage
        node:
          version: 16

      dependencies:
        before:
          - composer install
          - npm install
          - npm run build

      tests:
        override:
          - command: |
              rm -f var/test.db
              php bin/console doctrine:database:create --env=test || true
              php bin/console doctrine:migrations:migrate --env=test --no-interaction
              vendor/bin/phpunit --coverage-clover=var/coverage.clover
            coverage:
              file: var/coverage.clover
              format: php-clover

    analysis:
      tests:
        override:
          - php-scrutinizer-run

tools:
  php_code_coverage:
    enabled: true
    filter:
      excluded_paths:
        - 'src/Controller/*'
        - 'src/Entity/*'
        - 'src/DataFixtures/*'
        - 'src/Migrations/*'
        - 'src/Repository/*'
        - 'src/Service/*'
        - 'src/Kernel.php'
        - 'tests/*'
        - 'vendor/*'

