build:
  image: default-bionic

  nodes:
    analysis:
      environment:
        php:
          version: 8.2
        node:
          version: 16
      cache:
        directories:
          - vendor/
          - node_modules/
      commands:
        - pwd
        - ls -la
        - cd me/report
        - ls -la
        - npm install
        - mkdir -p docs
        - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
        - php-scrutinizer-run
