imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

artifacts:
    paths:
        - docs/coverage.clover

build:
    image: default-bionic

    nodes:
        analysis:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 16
            cache:
                directories:
                    - vendor/
                    - node_modules/
            commands:
                - npm --version
                - ls -la
                - ls -la package.json || echo "⚠️ Ingen package.json hittades!"
                - npm cache clean --force
                - npm ci || npm install
                - mkdir -p docs
                - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
                - php-scrutinizer-run
