imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    nodes:
        tests:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - command: "XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover"

tools:
    external_code_coverage:
        enabled: true
        filter:
            paths: ["docs/coverage.clover"]
