tools:
  php_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer: true
  php_cpd: true
  php_loc: true
  php_pdepend: true
  php_sim: true
  php_code_rating:
    enabled: true

imports:
  - php

filter:
  excluded_paths: [vendor/*, tests/*]

coding_style:
  php:
    braces: true
    indentation:
      general:
        size: 4
        use_tabs: false
      switch:
        indent_case: true
    spaces: true
    upper_lower_casing: true

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage
        node:
          version: 16

      dependencies:
        before:
          - composer install
          - npm install
          - npm run build

      tests:
        override:
          - command: |
              php bin/console doctrine:database:create --if-not-exists
              php bin/console doctrine:migrations:migrate --no-interaction
              vendor/bin/phpunit --coverage-clover=var/coverage.clover
            coverage:
              file: var/coverage.clover
              format: php-clover
