build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.1
          ini:
            xdebug.mode: coverage
        node:
          version: 16

      dependencies:
        before:
          - composer install
          - npm install
          - npm run build

      tests:
        override:
          - command: |
              # Ta bort eventuellt testdb (om SQLite)
              rm -f var/test.db

              # Skapa databas (utan --if-not-exists)
              php bin/console doctrine:database:create --env=test || true

              # Migrera databasen
              php bin/console doctrine:migrations:migrate --env=test --no-interaction

              # Kör testerna med kodtäckning
              vendor/bin/phpunit --coverage-clover=var/coverage.clover
            coverage:
              file: var/coverage.clover
              format: php-clover

    analysis:
      tests:
        override:
          - php-scrutinizer-run
