build:
  environment:
    php:
      version: 8.2
    node:
      version: 16

  commands:
    - cd $SCRUTINIZER_PROJECT_ROOT && composer install --no-interaction --prefer-dist --no-progress
    - cd $SCRUTINIZER_PROJECT_ROOT && npm ci || npm install
    - cd $SCRUTINIZER_PROJECT_ROOT && ./vendor/bin/phpstan analyse --level=max src
    - cd $SCRUTINIZER_PROJECT_ROOT && ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

tools:
  php_code_sniffer: true
  php_cpd: true
  php_cs_fixer:
    config: .php-cs-fixer.dist.php
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
