imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.3.3
          ini:
            xdebug.mode: coverage
      tests:
        override:
          - command: >
              mkdir -p docs &&
              ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
