imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  before_commands:
    - curl -sL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs

  nodes:
    tests:
      environment:
        php:
          version: 8.3.3
          ini:
            xdebug.mode: coverage
      tests:
        override:
          - command: >
              mkdir -p docs &&
              npm install &&
              ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover
