imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-jammy

    environment:
        node:
            version: "18"

    nodes:
        analysis:
        tests:
         override:
            - command: "composer install --no-interaction"
            - command: "vendor/bin/phpunit --coverage-clover=docs/coverage.clover"
        coverage:
            file: "docs/coverage.clover"
            format: "php-clover"
