imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - command: "composer phpunit"

tools:
    external_code_coverage:
        runs:
            - command: "composer phpunit"
              coverage_file: "docs/coverage.clover"
              format: "php-clover"
