build:
  nodes:
    scrutinizer:
      root_path: .
      environment:
        php:
          version: 8.1
      commands:
        - composer install --no-interaction --prefer-dist
        - mkdir -p var/logs
        - vendor/bin/phpunit --coverage-clover=var/coverage.clover

checks:
  php:
    coding_standard:
      name: Symfony

tools:
  php_code_sniffer: true
  php_cpd: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  php_cs_fixer: true
