imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - command: "XDEBUG_MODE=coverage composer phpunit"

tools:
    external_code_coverage:
        command: "XDEBUG_MODE=coverage composer phpunit"
        coverage_file: "docs/coverage.clover"
        format: "php-clover"
