build:
  image: default-bionic

  nodes:
    tests:
      environment:
        php:
          version: 8.2
      project_setup:
        override:
          - composer install --no-interaction --prefer-dist --optimize-autoloader
      tests:
        override:
          - mkdir -p docs
          - cd $SCRUTINIZER_BUILD_DIR
          - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

artifacts:
  paths:
    - docs/coverage.clover
