build:
  nodes:
    scrutinizer:
      root_path: .
      before_commands:
        - mkdir -p build/logs
      commands:
        - composer install --no-interaction --prefer-dist
        - vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=build/logs/clover.xml

artifacts:
  - build/logs/clover.xml

checks:
  php:
    coding_standard: PSR2
